name: bills_and_parts
description: Bills & Parts

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  toast: ^0.1.5
  flutter_riverpod: ^0.14.0+3
  sizer: ^2.0.13
  bitsdojo_window: ^0.1.1+1
  path_provider: ^2.0.2
  google_fonts: ^2.1.0
  font_awesome_flutter: ^9.1.0
  printing: ^5.2.1
  syncfusion_flutter_pdf: ^19.1.67-beta
  number_to_words: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: 2.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

#flutter pub run msix:create
msix_config:
  display_name: BillsAndParts
  publisher_display_name: hipoojan
  identity_name: com.hi.bills_and_parts
  msix_version: 1.0.3.3
  certificate_path: D:\Projects\Flutter\bills_and_parts\bandp.pfx
  certificate_password: bandp@123
  publisher: CN=HI, O=HI, L=India, S=Gujarat, C=IN
  logo_path: D:\Projects\Flutter\bills_and_parts\assets\logo.png
  start_menu_icon_path: D:\Projects\Flutter\bills_and_parts\assets\logo.png
  tile_icon_path: D:\Projects\Flutter\bills_and_parts\assets\logo.png
  vs_generated_images_folder_path: D:\Projects\Flutter\bills_and_parts\windows\runner\resources
  icons_background_color: transparent
  architecture: x64
  capabilities: 'removeableStorage,documentsLibrary'